### ISSUE TITLE
chrom fetch sizes has issues reading yeast chromosomes (latin numbering?)

### ISSUE THREAD

**Issue by Marlies1993** [mirnylab/bioframe#12]
Check output of `bioframe.fetch_chromsizes('sacCer3')` in screenshot. It seems like only chrX and chrM are fetched, possibly because chromosomes of yeast are labelled with latin numbering (?). 

Thank you!

![image](https://user-images.githubusercontent.com/16121171/58349056-46a10b00-7e30-11e9-9072-16bc7779dc34.png)

**Comment by gfudenberg** [comment]
good guess! did you try a chrom.sizes file with renamed chrms?

**Comment by Marlies1993** [comment]
Never mind, we just found the solution in the code! You can add a parameter. Running it likes this works:

`chromsizes = bioframe.fetch_chromsizes('sacCer3',all_names=True)`

**Comment by gfudenberg** [comment]
nice!

**Comment by golobor** [comment]
Nezar, this is not the first time people are running into this issue
(myself included, twice). Maybe we should set all_names to True by default?

Anton.
(typed on a phone, sorry for brevity and typos)
