### ISSUE TITLE
PyPi package is different from github repo

### ISSUE THREAD

**Issue by dmalzl** [mirnylab/bioframe#27]
I was recently checking out the cooltools suite and found that some functions used parts of the bioframe package that are not part of the module that could be installed via pip (i.e. PyPi) version.

I double-checked the version numbers and I have the latest bioframe version.

In particular this affects the `bioframe.bedslice` function which is used in the cooltools `cooltools.eigdecomp.cooler_cis_eigs` function to get the part of the phasing track matching the current region under decomposition. There it is used like defined in the repo here and also works as expected when using the cooltools function with a signature of
```
bedslice(frame, region)
```
However, when trying to use the `bedslice` directly it is a completely different function with a signature of 
```
bedslice(frame, chrom, start, end)
```

Is there any explanation for this?###

**Comment by nvictus** [comment]
We are in the process of refactoring bioframe. A new release of cooltools depending on the new bioframe will follow. If you are installing cooltools from master there was one recent commit that put it out of sync with the bioframe 0.0 series (https://github.com/mirnylab/cooltools/commit/a8ed7763a3ef3f0552a201b72bad4e8954763bcc).

I have an idea, @itsameerkat: let's revert that commit and make a cooltools 0.3.2 release that requires bioframe < 0.1.0. That will ensure cooltools 0.3 works in the future.

**Comment by nvictus** [comment]
@dmalzl cooltools v0.3.2 is now up on PyPI. Please give it a try and re-open if you still encounter problems.
