### ISSUE TITLE
Are bioframes designed to solve different problems than PyRanges? 

### ISSUE THREAD

**Issue by endrebak** [mirnylab/bioframe#40]
I am just wondering why/if you did not find pyranges satisfactory for some reason :)

**Comment by endrebak** [comment]
I am impressed with your pure-numpy implementations of overlap. I'll be reading your code base to get better at solving my problems without the crutch of Cython :)

You use the same license, so I guess I can steal your implementation to pyranges (with proper attribution of course). How would you feel about that? 

It might be weird if we are going to have papers competing for the same cites 🙃

**Comment by nvictus** [comment]
Hi Endre,

Thanks for reaching out! 

Part of the motivation for bioframe is historical. We split off bioframe as a support library for our other projects to handle loading, construction and basic manipulation of dataframes of genomic intervals. At that time, there were no libraries working with genomic interval dataframes. 

For interval arithmetic operations, we initially used a simple wrapper over the bedtools command line. More recently, as our other projects grew, we decided to implement the basic operations in pure numpy to have an API that is more intuitive for working with dataframes. One design decision was not to use an object wrapping the dataframe. In our Hi-C analyses, we do lots of streaming operations on large tables (such as cooler files) where the cost of roundtrip to-and-from interval tree structure would be costly. We also often deal with 2D intervals.

> You use the same license, so I guess I can use your implementation in pyranges (with proper attribution of course). How would you feel about that? 

You’re absolutely welcome to! :smile:  Part of doing the pure numpy implementation was to see whether it would be fast enough without the need for an interval tree data structure, and it seems like it is. 

We’re also very open to combining efforts. Let us know if you’d like to join us on one of our weekly developer calls to chat about it - they are every Tuesday at 3pm ET, and rotate between discussions of cooler, cooltools, and bioframe.

**Comment by endrebak** [comment]
Thanks for the reply.

Your implementation is similar to future updates I was mulling over. The current implementation of bioframe has many advantages over PyRanges (which I have realized in hindsight). You may know many of these, but by eschewing C/Cython in favor of NumPy, you

1) get terser, higher-level and less imperative code that is easier to reason about,
2) avoid the compilation step, so testing/development is easier,
3) need fewer dependencies.
 
And, lastly, my main reason for wanting to update pyranges was that

4) by only relying on NumPy/Python, free parallelism with dask or modin becomes possible. My Cython-implementations of the basic operations rely on data being stored together, contiguously. Therefore, dask and modin cannot be used with PyRanges.

I would love to join the meeting and hear about the possibilities for collaboration and your vision for bioframe. Like whether you want to include stuff that pyranges has like 

- reading/writing of bioinformatics file-formats,
- genomics-relevant/optimized functions for statistics
- stranded operations (opposite/same/nostrand)

3 PM ET seems to be nine of clock tonight. Send an invite to endrebak85@gmail.com, and I'll join :)

**Comment by endrebak** [comment]
Thanks for the meeting. Below is my summary, correct me if you disagree with anything or I misunderstood something:

# Summary

#### bioframes
- use a dataframe
- pure NumPy/pandas
- intended for the mirnylab and HiC-projects 
- available for everyone to use, but not meant as a general-purpose tool to solve every problem
- focus will be on implementing functionality useful for the developers
- should be fast enough, efficiency not the main goal

#### pyranges
- use a dict of dataframes (to avoid split and combine for every step)
- relies on homegrown compiled code, not just NumPy/pandas
- intended as a general-purpose genomics library
- goal of trying to accomodate user requests promptly
- should be the fastest way to do genomics in Python

# General thoughts

I was mistaken about dask - it is lower level than [modin](https://github.com/modin-project/modin). With modin however, it might be possible to build on bioframes (bigbioframes?) to create an even faster data structure than pyranges (at the cost of more CPU/memory use). 

I will follow the bioframe development out of personal interest, even though I do not need it myself.

# Possible action points?

Describe the use cases for bioframe and pyranges. For newbs, the READMEs will not be of help in choosing between the two.

**Comment by endrebak** [comment]
I would also be interested in participating in bioframe meetings btw, but I will mostly listen.

Some misunderstandings you might have had:

- pyranges does not build an interval data structure when created. It does so on-the-fly when needed.
- also, creating the interval data structures is almost instantaneous. Timing on 3 million intervals on 2011 iMac:

```
> import pyranges as or

> from ncls import NCLS

> gr = pr.random(int(3e6)).df

> %time NCLS(gr.Start.values, gr.End.values, gr.index.values)
CPU times: user 486 ms, sys: 7.66 ms, total: 494 ms
Wall time: 492 ms
```

**Comment by nvictus** [comment]
Glad you could join on short notice and thanks for all of your input and the and PR!

Perhaps we were not very clear in our description on the call and emphasized short-term goals over long-term. We almost certainly intend for bioframe to be a general-purpose library. We see the main difference between the two libraries as API choices and feature breadth.

With bioframe, we aimed for a lean but flexible API, consuming and returning dataframes, potentially at the expense of being slower. For example, by not explicitly incorporating strand, we open the possibility to use one or several other fields instead. However, given our API choices, we also want it to be fast and we may consider down the line switching to Cython-dependent code (or potentially using pyranges internally) if performance becomes a bottleneck. 

For now, we have limited resources, and want to achieve a well-documented implementation for a minimal set of genomic interval operations on pandas dataframes, sufficient to implement all other operations. Regarding future plans, at least 6 labs are connected to the development of bioframe so it is likely that someone would want to invest more time into the project. Currently, though we don’t intend to provide active support for new user requests. 

Re: on-the-fly ncls construction. I personally wasn't aware of that. Thanks for clarifying! Your under-the-hood implementations for NCLs and RLEs are something we should really take a look at. 

Re: modin. I am quite familiar with dask, but not modin. Looks interesting! Besides interval arithmetic, I think it might be cool to think together about dataframe reader/writers on indexed binary files like bam and bigwig. With an interface that can query ranges of intervals efficiently, it should be easy to plug those into dask to partition and work with large files out-of-core.

**Comment by endrebak** [comment]
Neat! Please ping me for anything. I am very interested in participating. The pyranges fundamentals are more or less complete and will only receive minor updates/bugfixes (I'll continue updating the libraries around pyranges instead, but make sure they are compatible with regular dfs so they can use bioframes too).
