### ISSUE TITLE
Citing bioframe?

### ISSUE THREAD

**Issue by endrebak** [mirnylab/bioframe#42]
How would I cite bioframe?

I am writing up my Ph.D. and discussing the merits/downsides of pyranges and bioframe.

I know you do not have a paper on it but it would be nice to have something to cite. Is it correct to say that bioframe was originally made to support cooler and other Hi-C software? Then I can cite cooler.

**Comment by nvictus** [comment]
We should register with zenodo, as with our other repos. I'll make that a todo.

**Comment by nvictus** [comment]
An initial DOI was just minted. https://doi.org/10.5281/zenodo.3897573 will refer to all releases and point to the latest one.
