### ISSUE TITLE
tests failing b/c of check_exact=True

### ISSUE THREAD

**Issue by golobor** [mirnylab/bioframe#49]
@gfudenberg , you should probably know, do we really need check_exact when we compare pyranges vs bioframe via assert_frame_equal?
https://github.com/mirnylab/bioframe/blob/0ee7a471b998c36e22254cb2ef98c336d7f2d770/tests/test_ops.py#L131
Our tests on github actions fail for some reason b/c of this flag. On my own machine, same tests pass :-/. Not sure why there is such a discrepancy, but setting check_exact=False could probably solve it.

**Comment by gfudenberg** [comment]
hmm, can't remember why I put that argument in! Seems like it (now) fails (with latest pandas) b/c of different dtypes for positions-- int32 vs int64. Happy to remove or cast everything to int64 earlier.

**Comment by golobor** [comment]
right, thank you - indeed it fails after upgrading pandas. I'll just set it to False for now.
