### ISSUE TITLE
frac_gc in tools.py throws error

### ISSUE THREAD

**Issue by itsameercat** [mirnylab/bioframe#7]
When I try to run frac_gc, I get the following error:

/home/sameer/miniconda3/lib/python3.6/site-packages/bioframe/tools.py in _each(chrom_group)
    149         for _, bin in chrom_group.iterrows():
    150             s = seq[bin.start:bin.end]
--> 151             g = s.count('G')
    152             g += s.count('g')
    153             c = s.count('C')

AttributeError: 'Sequence' object has no attribute 'count'

I think this is because the variable s is an OrderedDict() of <chrom_name> and associated FastaRecord. The fasta record needs to be a string variable before the count method can be used successfully.

**Comment by golobor** [comment]
I may or may not have fixed it in https://github.com/mirnylab/bioframe/commit/d0f6b74090986ac9e025d1bb713e5b4cfe609ef3
may I ask you to test the proposed fix?

**Comment by itsameercat** [comment]
Tested and issue seems resolved. Thanks!

**Comment by golobor** [comment]
thanks for reporting and testing!!
